### ISSUE TITLE
Updating predictions with golden labels

### ISSUE THREAD

**Issue by maayan1995** [yanzhh/HGERE#3]
Thanks for the great work on this project!
In the "evaluate" function in your code, this function is used:
https://github.com/yanzhh/HGERE/blob/e37ca9b08171b54d143642cf4ef50d3e4e0560f9/run_pruner.py#L976C1-L984C18

As I understand it, this uses the real labels of spans to update the labels given to predicted spans. This seems like something that should only be happening in evaluation during training and not when using "evaluate" function for final testing. when I use the code to test without passing real labels, as in a real world situation. there is a performance drop. 

Is this a known issue? Do you have any suggestions on overcoming the performance drop that will occur when using the model on unseen data?

**Comment by yanzhh** [comment]
Thank you for your interest in our project. Regarding your question, this was intentionally designed to simplify the modification to the base code of PL-marker's "run_ner.py". For a pruner, we only need to predict the span's mention correctly, as the label prediction is the task for the NER model. To minimize changes to the base code, the gold labels were included when evaluating the prediction of span mentions, so that as long as a span mention is predicted correctly, the model's prediction is considered correct.
